(cl:defpackage sagittarius_llm_control-srv
  (:use )
  (:export
   "DETECTBLOCK"
   "<DETECTBLOCK-REQUEST>"
   "DETECTBLOCK-REQUEST"
   "<DETECTBLOCK-RESPONSE>"
   "DETECTBLOCK-RESPONSE"
   "EXECUTENATURALLANGUAGETASK"
   "<EXECUTENATURALLANGUAGETASK-REQUEST>"
   "EXECUTENATURALLANGUAGETASK-REQUEST"
   "<EXECUTENATURALLANGUAGETASK-RESPONSE>"
   "EXECUTENATURALLANGUAGETASK-RESPONSE"
  ))

