// Generated by gencpp from file sagittarius_llm_control/DetectColoredBlock.msg
// DO NOT EDIT!


#ifndef SAGITTARIUS_LLM_CONTROL_MESSAGE_DETECTCOLOREDBLOCK_H
#define SAGITTARIUS_LLM_CONTROL_MESSAGE_DETECTCOLOREDBLOCK_H

#include <ros/service_traits.h>


#include <sagittarius_llm_control/DetectColoredBlockRequest.h>
#include <sagittarius_llm_control/DetectColoredBlockResponse.h>


namespace sagittarius_llm_control
{

struct DetectColoredBlock
{

typedef DetectColoredBlockRequest Request;
typedef DetectColoredBlockResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DetectColoredBlock
} // namespace sagittarius_llm_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sagittarius_llm_control::DetectColoredBlock > {
  static const char* value()
  {
    return "2067dc8c08ea01b0be7723ab7195563c";
  }

  static const char* value(const ::sagittarius_llm_control::DetectColoredBlock&) { return value(); }
};

template<>
struct DataType< ::sagittarius_llm_control::DetectColoredBlock > {
  static const char* value()
  {
    return "sagittarius_llm_control/DetectColoredBlock";
  }

  static const char* value(const ::sagittarius_llm_control::DetectColoredBlock&) { return value(); }
};


// service_traits::MD5Sum< ::sagittarius_llm_control::DetectColoredBlockRequest> should match
// service_traits::MD5Sum< ::sagittarius_llm_control::DetectColoredBlock >
template<>
struct MD5Sum< ::sagittarius_llm_control::DetectColoredBlockRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sagittarius_llm_control::DetectColoredBlock >::value();
  }
  static const char* value(const ::sagittarius_llm_control::DetectColoredBlockRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sagittarius_llm_control::DetectColoredBlockRequest> should match
// service_traits::DataType< ::sagittarius_llm_control::DetectColoredBlock >
template<>
struct DataType< ::sagittarius_llm_control::DetectColoredBlockRequest>
{
  static const char* value()
  {
    return DataType< ::sagittarius_llm_control::DetectColoredBlock >::value();
  }
  static const char* value(const ::sagittarius_llm_control::DetectColoredBlockRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sagittarius_llm_control::DetectColoredBlockResponse> should match
// service_traits::MD5Sum< ::sagittarius_llm_control::DetectColoredBlock >
template<>
struct MD5Sum< ::sagittarius_llm_control::DetectColoredBlockResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sagittarius_llm_control::DetectColoredBlock >::value();
  }
  static const char* value(const ::sagittarius_llm_control::DetectColoredBlockResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sagittarius_llm_control::DetectColoredBlockResponse> should match
// service_traits::DataType< ::sagittarius_llm_control::DetectColoredBlock >
template<>
struct DataType< ::sagittarius_llm_control::DetectColoredBlockResponse>
{
  static const char* value()
  {
    return DataType< ::sagittarius_llm_control::DetectColoredBlock >::value();
  }
  static const char* value(const ::sagittarius_llm_control::DetectColoredBlockResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SAGITTARIUS_LLM_CONTROL_MESSAGE_DETECTCOLOREDBLOCK_H
