// Generated by gencpp from file sagittarius_llm_control/DetectBlock.msg
// DO NOT EDIT!


#ifndef SAGITTARIUS_LLM_CONTROL_MESSAGE_DETECTBLOCK_H
#define SAGITTARIUS_LLM_CONTROL_MESSAGE_DETECTBLOCK_H

#include <ros/service_traits.h>


#include <sagittarius_llm_control/DetectBlockRequest.h>
#include <sagittarius_llm_control/DetectBlockResponse.h>


namespace sagittarius_llm_control
{

struct DetectBlock
{

typedef DetectBlockRequest Request;
typedef DetectBlockResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DetectBlock
} // namespace sagittarius_llm_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sagittarius_llm_control::DetectBlock > {
  static const char* value()
  {
    return "2067dc8c08ea01b0be7723ab7195563c";
  }

  static const char* value(const ::sagittarius_llm_control::DetectBlock&) { return value(); }
};

template<>
struct DataType< ::sagittarius_llm_control::DetectBlock > {
  static const char* value()
  {
    return "sagittarius_llm_control/DetectBlock";
  }

  static const char* value(const ::sagittarius_llm_control::DetectBlock&) { return value(); }
};


// service_traits::MD5Sum< ::sagittarius_llm_control::DetectBlockRequest> should match
// service_traits::MD5Sum< ::sagittarius_llm_control::DetectBlock >
template<>
struct MD5Sum< ::sagittarius_llm_control::DetectBlockRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sagittarius_llm_control::DetectBlock >::value();
  }
  static const char* value(const ::sagittarius_llm_control::DetectBlockRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sagittarius_llm_control::DetectBlockRequest> should match
// service_traits::DataType< ::sagittarius_llm_control::DetectBlock >
template<>
struct DataType< ::sagittarius_llm_control::DetectBlockRequest>
{
  static const char* value()
  {
    return DataType< ::sagittarius_llm_control::DetectBlock >::value();
  }
  static const char* value(const ::sagittarius_llm_control::DetectBlockRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sagittarius_llm_control::DetectBlockResponse> should match
// service_traits::MD5Sum< ::sagittarius_llm_control::DetectBlock >
template<>
struct MD5Sum< ::sagittarius_llm_control::DetectBlockResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sagittarius_llm_control::DetectBlock >::value();
  }
  static const char* value(const ::sagittarius_llm_control::DetectBlockResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sagittarius_llm_control::DetectBlockResponse> should match
// service_traits::DataType< ::sagittarius_llm_control::DetectBlock >
template<>
struct DataType< ::sagittarius_llm_control::DetectBlockResponse>
{
  static const char* value()
  {
    return DataType< ::sagittarius_llm_control::DetectBlock >::value();
  }
  static const char* value(const ::sagittarius_llm_control::DetectBlockResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SAGITTARIUS_LLM_CONTROL_MESSAGE_DETECTBLOCK_H
