// Generated by gencpp from file sagittarius_llm_control/DetectColoredBlockRequest.msg
// DO NOT EDIT!


#ifndef SAGITTARIUS_LLM_CONTROL_MESSAGE_DETECTCOLOREDBLOCKREQUEST_H
#define SAGITTARIUS_LLM_CONTROL_MESSAGE_DETECTCOLOREDBLOCKREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sagittarius_llm_control
{
template <class ContainerAllocator>
struct DetectColoredBlockRequest_
{
  typedef DetectColoredBlockRequest_<ContainerAllocator> Type;

  DetectColoredBlockRequest_()
    : target_label()  {
    }
  DetectColoredBlockRequest_(const ContainerAllocator& _alloc)
    : target_label(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _target_label_type;
  _target_label_type target_label;





  typedef boost::shared_ptr< ::sagittarius_llm_control::DetectColoredBlockRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sagittarius_llm_control::DetectColoredBlockRequest_<ContainerAllocator> const> ConstPtr;

}; // struct DetectColoredBlockRequest_

typedef ::sagittarius_llm_control::DetectColoredBlockRequest_<std::allocator<void> > DetectColoredBlockRequest;

typedef boost::shared_ptr< ::sagittarius_llm_control::DetectColoredBlockRequest > DetectColoredBlockRequestPtr;
typedef boost::shared_ptr< ::sagittarius_llm_control::DetectColoredBlockRequest const> DetectColoredBlockRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sagittarius_llm_control::DetectColoredBlockRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sagittarius_llm_control::DetectColoredBlockRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sagittarius_llm_control::DetectColoredBlockRequest_<ContainerAllocator1> & lhs, const ::sagittarius_llm_control::DetectColoredBlockRequest_<ContainerAllocator2> & rhs)
{
  return lhs.target_label == rhs.target_label;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sagittarius_llm_control::DetectColoredBlockRequest_<ContainerAllocator1> & lhs, const ::sagittarius_llm_control::DetectColoredBlockRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sagittarius_llm_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::sagittarius_llm_control::DetectColoredBlockRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sagittarius_llm_control::DetectColoredBlockRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sagittarius_llm_control::DetectColoredBlockRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sagittarius_llm_control::DetectColoredBlockRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sagittarius_llm_control::DetectColoredBlockRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sagittarius_llm_control::DetectColoredBlockRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sagittarius_llm_control::DetectColoredBlockRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9ad3ebebe1c71e72c4cd6a2be519ffd8";
  }

  static const char* value(const ::sagittarius_llm_control::DetectColoredBlockRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9ad3ebebe1c71e72ULL;
  static const uint64_t static_value2 = 0xc4cd6a2be519ffd8ULL;
};

template<class ContainerAllocator>
struct DataType< ::sagittarius_llm_control::DetectColoredBlockRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sagittarius_llm_control/DetectColoredBlockRequest";
  }

  static const char* value(const ::sagittarius_llm_control::DetectColoredBlockRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sagittarius_llm_control::DetectColoredBlockRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string target_label\n"
;
  }

  static const char* value(const ::sagittarius_llm_control::DetectColoredBlockRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sagittarius_llm_control::DetectColoredBlockRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.target_label);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DetectColoredBlockRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sagittarius_llm_control::DetectColoredBlockRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sagittarius_llm_control::DetectColoredBlockRequest_<ContainerAllocator>& v)
  {
    s << indent << "target_label: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.target_label);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SAGITTARIUS_LLM_CONTROL_MESSAGE_DETECTCOLOREDBLOCKREQUEST_H
