// Generated by gencpp from file sagittarius_llm_control/DetectBlockResponse.msg
// DO NOT EDIT!


#ifndef SAGITTARIUS_LLM_CONTROL_MESSAGE_DETECTBLOCKRESPONSE_H
#define SAGITTARIUS_LLM_CONTROL_MESSAGE_DETECTBLOCKRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace sagittarius_llm_control
{
template <class ContainerAllocator>
struct DetectBlockResponse_
{
  typedef DetectBlockResponse_<ContainerAllocator> Type;

  DetectBlockResponse_()
    : success(false)
    , detected_label()
    , confidence(0.0)
    , center_u(0)
    , center_v(0)
    , position()
    , error()  {
    }
  DetectBlockResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , detected_label(_alloc)
    , confidence(0.0)
    , center_u(0)
    , center_v(0)
    , position(_alloc)
    , error(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _detected_label_type;
  _detected_label_type detected_label;

   typedef float _confidence_type;
  _confidence_type confidence;

   typedef int32_t _center_u_type;
  _center_u_type center_u;

   typedef int32_t _center_v_type;
  _center_v_type center_v;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _position_type;
  _position_type position;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _error_type;
  _error_type error;





  typedef boost::shared_ptr< ::sagittarius_llm_control::DetectBlockResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sagittarius_llm_control::DetectBlockResponse_<ContainerAllocator> const> ConstPtr;

}; // struct DetectBlockResponse_

typedef ::sagittarius_llm_control::DetectBlockResponse_<std::allocator<void> > DetectBlockResponse;

typedef boost::shared_ptr< ::sagittarius_llm_control::DetectBlockResponse > DetectBlockResponsePtr;
typedef boost::shared_ptr< ::sagittarius_llm_control::DetectBlockResponse const> DetectBlockResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sagittarius_llm_control::DetectBlockResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sagittarius_llm_control::DetectBlockResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sagittarius_llm_control::DetectBlockResponse_<ContainerAllocator1> & lhs, const ::sagittarius_llm_control::DetectBlockResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.detected_label == rhs.detected_label &&
    lhs.confidence == rhs.confidence &&
    lhs.center_u == rhs.center_u &&
    lhs.center_v == rhs.center_v &&
    lhs.position == rhs.position &&
    lhs.error == rhs.error;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sagittarius_llm_control::DetectBlockResponse_<ContainerAllocator1> & lhs, const ::sagittarius_llm_control::DetectBlockResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sagittarius_llm_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::sagittarius_llm_control::DetectBlockResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sagittarius_llm_control::DetectBlockResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sagittarius_llm_control::DetectBlockResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sagittarius_llm_control::DetectBlockResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sagittarius_llm_control::DetectBlockResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sagittarius_llm_control::DetectBlockResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sagittarius_llm_control::DetectBlockResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9c128f12f77a2059644c6c86a5e19e85";
  }

  static const char* value(const ::sagittarius_llm_control::DetectBlockResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9c128f12f77a2059ULL;
  static const uint64_t static_value2 = 0x644c6c86a5e19e85ULL;
};

template<class ContainerAllocator>
struct DataType< ::sagittarius_llm_control::DetectBlockResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sagittarius_llm_control/DetectBlockResponse";
  }

  static const char* value(const ::sagittarius_llm_control::DetectBlockResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sagittarius_llm_control::DetectBlockResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"string detected_label\n"
"float32 confidence\n"
"int32 center_u\n"
"int32 center_v\n"
"geometry_msgs/Point position\n"
"string error\n"
"\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::sagittarius_llm_control::DetectBlockResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sagittarius_llm_control::DetectBlockResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.detected_label);
      stream.next(m.confidence);
      stream.next(m.center_u);
      stream.next(m.center_v);
      stream.next(m.position);
      stream.next(m.error);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DetectBlockResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sagittarius_llm_control::DetectBlockResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sagittarius_llm_control::DetectBlockResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "detected_label: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.detected_label);
    s << indent << "confidence: ";
    Printer<float>::stream(s, indent + "  ", v.confidence);
    s << indent << "center_u: ";
    Printer<int32_t>::stream(s, indent + "  ", v.center_u);
    s << indent << "center_v: ";
    Printer<int32_t>::stream(s, indent + "  ", v.center_v);
    s << indent << "position: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
    s << indent << "error: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.error);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SAGITTARIUS_LLM_CONTROL_MESSAGE_DETECTBLOCKRESPONSE_H
