// Generated by gencpp from file sagittarius_llm_control/ExecuteNaturalLanguageTaskResponse.msg
// DO NOT EDIT!


#ifndef SAGITTARIUS_LLM_CONTROL_MESSAGE_EXECUTENATURALLANGUAGETASKRESPONSE_H
#define SAGITTARIUS_LLM_CONTROL_MESSAGE_EXECUTENATURALLANGUAGETASKRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sagittarius_llm_control
{
template <class ContainerAllocator>
struct ExecuteNaturalLanguageTaskResponse_
{
  typedef ExecuteNaturalLanguageTaskResponse_<ContainerAllocator> Type;

  ExecuteNaturalLanguageTaskResponse_()
    : success(false)
    , summary()
    , plan_json()
    , error()  {
    }
  ExecuteNaturalLanguageTaskResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , summary(_alloc)
    , plan_json(_alloc)
    , error(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _summary_type;
  _summary_type summary;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _plan_json_type;
  _plan_json_type plan_json;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _error_type;
  _error_type error;





  typedef boost::shared_ptr< ::sagittarius_llm_control::ExecuteNaturalLanguageTaskResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sagittarius_llm_control::ExecuteNaturalLanguageTaskResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ExecuteNaturalLanguageTaskResponse_

typedef ::sagittarius_llm_control::ExecuteNaturalLanguageTaskResponse_<std::allocator<void> > ExecuteNaturalLanguageTaskResponse;

typedef boost::shared_ptr< ::sagittarius_llm_control::ExecuteNaturalLanguageTaskResponse > ExecuteNaturalLanguageTaskResponsePtr;
typedef boost::shared_ptr< ::sagittarius_llm_control::ExecuteNaturalLanguageTaskResponse const> ExecuteNaturalLanguageTaskResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sagittarius_llm_control::ExecuteNaturalLanguageTaskResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sagittarius_llm_control::ExecuteNaturalLanguageTaskResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sagittarius_llm_control::ExecuteNaturalLanguageTaskResponse_<ContainerAllocator1> & lhs, const ::sagittarius_llm_control::ExecuteNaturalLanguageTaskResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.summary == rhs.summary &&
    lhs.plan_json == rhs.plan_json &&
    lhs.error == rhs.error;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sagittarius_llm_control::ExecuteNaturalLanguageTaskResponse_<ContainerAllocator1> & lhs, const ::sagittarius_llm_control::ExecuteNaturalLanguageTaskResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sagittarius_llm_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::sagittarius_llm_control::ExecuteNaturalLanguageTaskResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sagittarius_llm_control::ExecuteNaturalLanguageTaskResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sagittarius_llm_control::ExecuteNaturalLanguageTaskResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sagittarius_llm_control::ExecuteNaturalLanguageTaskResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sagittarius_llm_control::ExecuteNaturalLanguageTaskResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sagittarius_llm_control::ExecuteNaturalLanguageTaskResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sagittarius_llm_control::ExecuteNaturalLanguageTaskResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "82ab653f3cc31c8822b11fe7224c5224";
  }

  static const char* value(const ::sagittarius_llm_control::ExecuteNaturalLanguageTaskResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x82ab653f3cc31c88ULL;
  static const uint64_t static_value2 = 0x22b11fe7224c5224ULL;
};

template<class ContainerAllocator>
struct DataType< ::sagittarius_llm_control::ExecuteNaturalLanguageTaskResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sagittarius_llm_control/ExecuteNaturalLanguageTaskResponse";
  }

  static const char* value(const ::sagittarius_llm_control::ExecuteNaturalLanguageTaskResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sagittarius_llm_control::ExecuteNaturalLanguageTaskResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"string summary\n"
"string plan_json\n"
"string error\n"
"\n"
;
  }

  static const char* value(const ::sagittarius_llm_control::ExecuteNaturalLanguageTaskResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sagittarius_llm_control::ExecuteNaturalLanguageTaskResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.summary);
      stream.next(m.plan_json);
      stream.next(m.error);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ExecuteNaturalLanguageTaskResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sagittarius_llm_control::ExecuteNaturalLanguageTaskResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sagittarius_llm_control::ExecuteNaturalLanguageTaskResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "summary: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.summary);
    s << indent << "plan_json: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.plan_json);
    s << indent << "error: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.error);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SAGITTARIUS_LLM_CONTROL_MESSAGE_EXECUTENATURALLANGUAGETASKRESPONSE_H
