// Generated by gencpp from file sagittarius_llm_control/ExecuteNaturalLanguageTaskRequest.msg
// DO NOT EDIT!


#ifndef SAGITTARIUS_LLM_CONTROL_MESSAGE_EXECUTENATURALLANGUAGETASKREQUEST_H
#define SAGITTARIUS_LLM_CONTROL_MESSAGE_EXECUTENATURALLANGUAGETASKREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sagittarius_llm_control
{
template <class ContainerAllocator>
struct ExecuteNaturalLanguageTaskRequest_
{
  typedef ExecuteNaturalLanguageTaskRequest_<ContainerAllocator> Type;

  ExecuteNaturalLanguageTaskRequest_()
    : text()
    , plan_only(false)  {
    }
  ExecuteNaturalLanguageTaskRequest_(const ContainerAllocator& _alloc)
    : text(_alloc)
    , plan_only(false)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _text_type;
  _text_type text;

   typedef uint8_t _plan_only_type;
  _plan_only_type plan_only;





  typedef boost::shared_ptr< ::sagittarius_llm_control::ExecuteNaturalLanguageTaskRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sagittarius_llm_control::ExecuteNaturalLanguageTaskRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ExecuteNaturalLanguageTaskRequest_

typedef ::sagittarius_llm_control::ExecuteNaturalLanguageTaskRequest_<std::allocator<void> > ExecuteNaturalLanguageTaskRequest;

typedef boost::shared_ptr< ::sagittarius_llm_control::ExecuteNaturalLanguageTaskRequest > ExecuteNaturalLanguageTaskRequestPtr;
typedef boost::shared_ptr< ::sagittarius_llm_control::ExecuteNaturalLanguageTaskRequest const> ExecuteNaturalLanguageTaskRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sagittarius_llm_control::ExecuteNaturalLanguageTaskRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sagittarius_llm_control::ExecuteNaturalLanguageTaskRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sagittarius_llm_control::ExecuteNaturalLanguageTaskRequest_<ContainerAllocator1> & lhs, const ::sagittarius_llm_control::ExecuteNaturalLanguageTaskRequest_<ContainerAllocator2> & rhs)
{
  return lhs.text == rhs.text &&
    lhs.plan_only == rhs.plan_only;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sagittarius_llm_control::ExecuteNaturalLanguageTaskRequest_<ContainerAllocator1> & lhs, const ::sagittarius_llm_control::ExecuteNaturalLanguageTaskRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sagittarius_llm_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::sagittarius_llm_control::ExecuteNaturalLanguageTaskRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sagittarius_llm_control::ExecuteNaturalLanguageTaskRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sagittarius_llm_control::ExecuteNaturalLanguageTaskRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sagittarius_llm_control::ExecuteNaturalLanguageTaskRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sagittarius_llm_control::ExecuteNaturalLanguageTaskRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sagittarius_llm_control::ExecuteNaturalLanguageTaskRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sagittarius_llm_control::ExecuteNaturalLanguageTaskRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e8adab1fa36d297994265126c222f182";
  }

  static const char* value(const ::sagittarius_llm_control::ExecuteNaturalLanguageTaskRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe8adab1fa36d2979ULL;
  static const uint64_t static_value2 = 0x94265126c222f182ULL;
};

template<class ContainerAllocator>
struct DataType< ::sagittarius_llm_control::ExecuteNaturalLanguageTaskRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sagittarius_llm_control/ExecuteNaturalLanguageTaskRequest";
  }

  static const char* value(const ::sagittarius_llm_control::ExecuteNaturalLanguageTaskRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sagittarius_llm_control::ExecuteNaturalLanguageTaskRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string text\n"
"bool plan_only\n"
;
  }

  static const char* value(const ::sagittarius_llm_control::ExecuteNaturalLanguageTaskRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sagittarius_llm_control::ExecuteNaturalLanguageTaskRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.text);
      stream.next(m.plan_only);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ExecuteNaturalLanguageTaskRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sagittarius_llm_control::ExecuteNaturalLanguageTaskRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sagittarius_llm_control::ExecuteNaturalLanguageTaskRequest_<ContainerAllocator>& v)
  {
    s << indent << "text: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.text);
    s << indent << "plan_only: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.plan_only);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SAGITTARIUS_LLM_CONTROL_MESSAGE_EXECUTENATURALLANGUAGETASKREQUEST_H
