// Generated by gencpp from file sagittarius_llm_control/ExecuteNaturalLanguageTask.msg
// DO NOT EDIT!


#ifndef SAGITTARIUS_LLM_CONTROL_MESSAGE_EXECUTENATURALLANGUAGETASK_H
#define SAGITTARIUS_LLM_CONTROL_MESSAGE_EXECUTENATURALLANGUAGETASK_H

#include <ros/service_traits.h>


#include <sagittarius_llm_control/ExecuteNaturalLanguageTaskRequest.h>
#include <sagittarius_llm_control/ExecuteNaturalLanguageTaskResponse.h>


namespace sagittarius_llm_control
{

struct ExecuteNaturalLanguageTask
{

typedef ExecuteNaturalLanguageTaskRequest Request;
typedef ExecuteNaturalLanguageTaskResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ExecuteNaturalLanguageTask
} // namespace sagittarius_llm_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sagittarius_llm_control::ExecuteNaturalLanguageTask > {
  static const char* value()
  {
    return "be00a685ab6aa4e4d8c4b100b3f5f4c6";
  }

  static const char* value(const ::sagittarius_llm_control::ExecuteNaturalLanguageTask&) { return value(); }
};

template<>
struct DataType< ::sagittarius_llm_control::ExecuteNaturalLanguageTask > {
  static const char* value()
  {
    return "sagittarius_llm_control/ExecuteNaturalLanguageTask";
  }

  static const char* value(const ::sagittarius_llm_control::ExecuteNaturalLanguageTask&) { return value(); }
};


// service_traits::MD5Sum< ::sagittarius_llm_control::ExecuteNaturalLanguageTaskRequest> should match
// service_traits::MD5Sum< ::sagittarius_llm_control::ExecuteNaturalLanguageTask >
template<>
struct MD5Sum< ::sagittarius_llm_control::ExecuteNaturalLanguageTaskRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sagittarius_llm_control::ExecuteNaturalLanguageTask >::value();
  }
  static const char* value(const ::sagittarius_llm_control::ExecuteNaturalLanguageTaskRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sagittarius_llm_control::ExecuteNaturalLanguageTaskRequest> should match
// service_traits::DataType< ::sagittarius_llm_control::ExecuteNaturalLanguageTask >
template<>
struct DataType< ::sagittarius_llm_control::ExecuteNaturalLanguageTaskRequest>
{
  static const char* value()
  {
    return DataType< ::sagittarius_llm_control::ExecuteNaturalLanguageTask >::value();
  }
  static const char* value(const ::sagittarius_llm_control::ExecuteNaturalLanguageTaskRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sagittarius_llm_control::ExecuteNaturalLanguageTaskResponse> should match
// service_traits::MD5Sum< ::sagittarius_llm_control::ExecuteNaturalLanguageTask >
template<>
struct MD5Sum< ::sagittarius_llm_control::ExecuteNaturalLanguageTaskResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sagittarius_llm_control::ExecuteNaturalLanguageTask >::value();
  }
  static const char* value(const ::sagittarius_llm_control::ExecuteNaturalLanguageTaskResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sagittarius_llm_control::ExecuteNaturalLanguageTaskResponse> should match
// service_traits::DataType< ::sagittarius_llm_control::ExecuteNaturalLanguageTask >
template<>
struct DataType< ::sagittarius_llm_control::ExecuteNaturalLanguageTaskResponse>
{
  static const char* value()
  {
    return DataType< ::sagittarius_llm_control::ExecuteNaturalLanguageTask >::value();
  }
  static const char* value(const ::sagittarius_llm_control::ExecuteNaturalLanguageTaskResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SAGITTARIUS_LLM_CONTROL_MESSAGE_EXECUTENATURALLANGUAGETASK_H
